/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0e1512",
        surface: "#0e1512",
        "surface-dim": "#0e1512",
        "surface-bright": "#333b38",
        "surface-container-lowest": "#09100d",
        "surface-container-low": "#161d1b",
        "surface-container": "#1a211f",
        "surface-container-high": "#242c29",
        "surface-container-highest": "#2f3633",
        "surface-variant": "#2f3633",
        "surface-tint": "#38debb",
        "on-background": "#dde4e0",
        "on-surface": "#dde4e0",
        "on-surface-variant": "#bacac3",
        outline: "#85948e",
        "outline-variant": "#3c4a45",
        primary: "#ffffff",
        "on-primary": "#00382d",
        "primary-container": "#5ffbd6",
        "on-primary-container": "#00725e",
        "primary-fixed": "#5ffbd6",
        "primary-fixed-dim": "#38debb",
        "on-primary-fixed": "#002019",
        "on-primary-fixed-variant": "#005142",
        "inverse-primary": "#006b58",
        secondary: "#b6c6ed",
        "on-secondary": "#20304f",
        "secondary-container": "#374767",
        "on-secondary-container": "#a5b5db",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b6c6ed",
        "on-secondary-fixed": "#091b39",
        "on-secondary-fixed-variant": "#374767",
        tertiary: "#ffffff",
        "on-tertiary": "#233148",
        "tertiary-container": "#d6e3ff",
        "on-tertiary-container": "#57657e",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#b9c7e4",
        "on-tertiary-fixed": "#0d1c32",
        "on-tertiary-fixed-variant": "#39475f",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dde4e0",
        "inverse-on-surface": "#2b322f",
        // Etats operationnels utilises tels quels dans les maquettes.
        critical: "#f43f5e",
        warning: "#f59e0b",
        success: "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        pill: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
