/** @type {import('tailwindcss').Config} */

function token(name) {
  return `rgb(var(${name}) / <alpha-value>)`;
}

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: token("--color-background"),
        surface: token("--color-surface"),
        "surface-dim": token("--color-surface-dim"),
        "surface-bright": token("--color-surface-bright"),
        "surface-container-lowest": token("--color-surface-container-lowest"),
        "surface-container-low": token("--color-surface-container-low"),
        "surface-container": token("--color-surface-container"),
        "surface-container-high": token("--color-surface-container-high"),
        "surface-container-highest": token("--color-surface-container-highest"),
        "surface-variant": token("--color-surface-variant"),
        "surface-tint": token("--color-surface-tint"),
        "on-background": token("--color-on-background"),
        "on-surface": token("--color-on-surface"),
        "on-surface-variant": token("--color-on-surface-variant"),
        outline: token("--color-outline"),
        "outline-variant": token("--color-outline-variant"),
        primary: token("--color-primary"),
        "on-primary": token("--color-on-primary"),
        "primary-container": token("--color-primary-container"),
        "on-primary-container": token("--color-on-primary-container"),
        "primary-fixed": token("--color-primary-fixed"),
        "primary-fixed-dim": token("--color-primary-fixed-dim"),
        "on-primary-fixed": token("--color-on-primary-fixed"),
        "on-primary-fixed-variant": token("--color-on-primary-fixed-variant"),
        "inverse-primary": token("--color-inverse-primary"),
        secondary: token("--color-secondary"),
        "on-secondary": token("--color-on-secondary"),
        "secondary-container": token("--color-secondary-container"),
        "on-secondary-container": token("--color-on-secondary-container"),
        "secondary-fixed": token("--color-secondary-fixed"),
        "secondary-fixed-dim": token("--color-secondary-fixed-dim"),
        "on-secondary-fixed": token("--color-on-secondary-fixed"),
        "on-secondary-fixed-variant": token("--color-on-secondary-fixed-variant"),
        tertiary: token("--color-tertiary"),
        "on-tertiary": token("--color-on-tertiary"),
        "tertiary-container": token("--color-tertiary-container"),
        "on-tertiary-container": token("--color-on-tertiary-container"),
        "tertiary-fixed": token("--color-tertiary-fixed"),
        "tertiary-fixed-dim": token("--color-tertiary-fixed-dim"),
        "on-tertiary-fixed": token("--color-on-tertiary-fixed"),
        "on-tertiary-fixed-variant": token("--color-on-tertiary-fixed-variant"),
        error: token("--color-error"),
        "on-error": token("--color-on-error"),
        "error-container": token("--color-error-container"),
        "on-error-container": token("--color-on-error-container"),
        "inverse-surface": token("--color-inverse-surface"),
        "inverse-on-surface": token("--color-inverse-on-surface"),
        critical: token("--color-critical"),
        warning: token("--color-warning"),
        success: token("--color-success"),
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        pill: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
